[package]
name = "ddcpoll"
version = "0.2.0"
authors = ["Mateusz Lenik <mlen@mlen.pl>"]
description = "DDC VCP poller"

[dependencies]
ddc-hi = "0.1.3"
toml = "0.4"
serde_derive = "1.0.76"
serde = "1.0.76"
clap = "2.32.0"